# Generated by Django 3.1.5 on 2021-01-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('type_food', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
                ('amount_reviews', models.IntegerField()),
                ('review_link', models.CharField(max_length=300)),
            ],
        ),
    ]
