# Generated by Django 3.1.5 on 2021-02-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='interests',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='types_of_food',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
