# Generated by Django 3.1.5 on 2021-03-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20210214_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='time_of_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='type_of_holiday',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
