# Generated by Django 3.1.5 on 2021-03-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20210304_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('rating', models.FloatField()),
                ('amount_reviews', models.IntegerField()),
                ('review_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='afternoon_activity',
            field=models.ForeignKey(db_column='afternoon_activity', on_delete=django.db.models.deletion.PROTECT, related_name='afternoon_activity', to='restaurants.attraction'),
        ),
        migrations.AlterField(
            model_name='case',
            name='morning_activity',
            field=models.ForeignKey(db_column='morning_activity', on_delete=django.db.models.deletion.PROTECT, related_name='morning_activity', to='restaurants.attraction'),
        ),
    ]
