# Generated by Django 3.1.5 on 2021-03-12 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_auto_20210131_1530'),
        ('restaurants', '0006_auto_20210312_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='afternoon_activity',
            field=models.ForeignKey(db_column='afternoon_activity', on_delete=django.db.models.deletion.PROTECT, related_name='afternoon_activity', to='attractions.attraction'),
        ),
        migrations.AlterField(
            model_name='case',
            name='morning_activity',
            field=models.ForeignKey(db_column='morning_activity', on_delete=django.db.models.deletion.PROTECT, related_name='morning_activity', to='attractions.attraction'),
        ),
        migrations.DeleteModel(
            name='Attraction',
        ),
    ]
