# Generated by Django 3.1.5 on 2021-03-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_auto_20210320_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
